### ISSUE TITLE
Commenting system for replies and questions

### ISSUE THREAD

**Issue by ananyo2012** [NIT-dgp/cat-forum#33]
This is a `break-me-up` issue. This means this is a big feature request / issue that is fragmented into smaller issues. Close this after each one of them is resolved.
****

A good commenting system is what makes a blog or forum more engaging. We need a design suggestions for this too. These are the steps to solve this issue

- [ ] Create Comment model and migration: #62
- [ ] Create a comments_controller and views for showing comments: #61
- [ ] Make comments section collapsible for more no of comments: #63
- [ ] Create expandable comment box: #64
