### ISSUE TITLE
Create Tagging system for threads

### ISSUE THREAD

**Issue by ananyo2012** [NIT-dgp/cat-forum#38]
This is a `break-me-up` issue. This means this is a big feature request / issue that is fragmented into smaller issues. Close this after each one of them is resolved.
****
Tags are in fact the most popular feature in blog posts and Q & A sites these days. So why not for the CAT-Forum. Tags make it easy to search specific and related content easily. We can use the [acts-as-taggable-on](https://github.com/mbleigh/acts-as-taggable-on) gem for creating a tagging system. These are the issues that need to be solved

- [ ] Use [acts-as-taggable-on](https://github.com/mbleigh/acts-as-taggable-on) and extend it over `NewThread` model: #66
- [ ] Create tags controller and views to list tag content: #68
- [ ] Create a tag input using [selectize](http://selectize.github.io/selectize.js/): #67
