### ISSUE TITLE
email notification system for new threads and replies

### ISSUE THREAD

**Issue by ananyo2012** [NIT-dgp/cat-forum#40]
This is a `break-me-up` issue. This means this is a big feature request / issue that is fragmented into smaller issues. Close this after each one of them is resolved.
****
email notifications are a good way to give regular notifications to users for their posted threads and answers. We should also create a subscription system where users can subscribe to tags for specific topics and email notifications will be sent to them whenever a new thread related to that topic is posted. Discussion on this is welcome. _Rails Action Mailer_ is a splendid way to implement this. Read the [Action Mailer doc](http://guides.rubyonrails.org/action_mailer_basics.html) before starting.

- [ ] Create Thread mailer: #71
- [ ] Create Reply mailer: #69
- [ ] Create Comment mailer: #70
